id: I8618CF47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:09:56+00:00'
last_modified: '2022-06-16T04:15:05.328243+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18339
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    533B:
      image_group_id: I8LS18344
      title: Volume 1 of gsung 'bum/ blo gros rgya mtsho/
      total_pages: 560
      order: 1
      base_file: 533B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
